
function Forward_simu_spots_exp_after_geo_fit(DS_fit,ParaFit, ...
    Rsample,RecVolumePixel,tomo_scale,ExpTime,atomparam,proj,Spots,rot_start,rot_step, ...
    S,B,Ahkl,nrhkl,hkl_square,Energy,lambda,V,K1,I0E,thetamax,lambda_min,lambda_max, ...
    P0y,P0z,pixelysize,pixelzsize,dety0,detz0,detysize,detzsize,BeamStopY,BeamStopZ, ...
    simap_data_flag,OutputFolder,rot_angles)

Lsam2sou=ParaFit(1);
Lsam2det=ParaFit(2);
dety00=ParaFit(3);
detz00=ParaFit(4);
tilt_x=ParaFit(5);
tilt_y=ParaFit(6);
tilt_z=ParaFit(7);
RotX=[1 0 0; 0 cosd(tilt_x) -sind(tilt_x); 0 sind(tilt_x) cosd(tilt_x)];
RotY=[cosd(tilt_y) 0 sind(tilt_y);0 1 0;-sind(tilt_y) 0 cosd(tilt_y)];
RotZ=[cosd(tilt_z) -sind(tilt_z) 0;sind(tilt_z) cosd(tilt_z) 0;0 0 1];
RotDet=RotX*RotY*RotZ;

if ispc
    Forward_simu_spots_exp(DS_fit, ...
        Rsample,RecVolumePixel,tomo_scale,ExpTime,atomparam,proj,Spots,rot_start,rot_step, ...
        S,B,Ahkl,nrhkl,hkl_square,Energy,lambda,V,K1,I0E,RotDet,thetamax,lambda_min,lambda_max,Lsam2sou,Lsam2det, ...
        dety00,detz00,P0y,P0z,pixelysize,pixelzsize,dety0,detz0,detysize,detzsize,BeamStopY,BeamStopZ, ...
        simap_data_flag,strcat(OutputFolder,'\verify_afterfit'),rot_angles);
elseif isunix || ismac
    Forward_simu_spots_exp(DS_fit, ...
    Rsample,RecVolumePixel,tomo_scale,ExpTime,atomparam,proj,Spots,rot_start,rot_step, ...
    S,B,Ahkl,nrhkl,hkl_square,Energy,lambda,V,K1,I0E,RotDet,thetamax,lambda_min,lambda_max,Lsam2sou,Lsam2det, ...
    dety00,detz00,P0y,P0z,pixelysize,pixelzsize,dety0,detz0,detysize,detzsize,BeamStopY,BeamStopZ, ...
    simap_data_flag,strcat(OutputFolder,'/verify_afterfit'),rot_angles);
end