
function Forward_simu_spots_exp_after_geo_fit(DS_fit,ParaFit, ...
    Rsample,RecVolumePixel,tomo_scale,ExpTime,atomparam,proj,Spots,rot_start,rot_step, ...
    S,B,Ahkl,nrhkl,hkl_square,Energy,lambda,V,K1,I0E,thetamax,lambda_min,lambda_max, ...
    P0y,P0z,RotAxisOffset,pixelysize,pixelzsize,dety0,detz0,detysize,detzsize,BeamStopY,BeamStopZ, ...
    simap_data_flag,OutputFolder,rot_angles)

Lsam2sou=ParaFit(1);
Lsam2det=ParaFit(2);
dety00=ParaFit(3);
detz00=ParaFit(4);
tilt_x=ParaFit(5);
tilt_y=ParaFit(6);
tilt_z=ParaFit(7);
RotDet=get_det_R(tilt_x,tilt_y,tilt_z);

if ispc
    Forward_simu_spots_exp(DS_fit, ...
        Rsample,RecVolumePixel,tomo_scale,ExpTime,atomparam,proj,Spots,rot_start,rot_step, ...
        S,B,Ahkl,nrhkl,hkl_square,Energy,lambda,V,K1,I0E,RotDet,thetamax,lambda_min,lambda_max,Lsam2sou,Lsam2det, ...
        dety00,detz00,P0y,P0z,RotAxisOffset,pixelysize,pixelzsize,dety0,detz0,detysize,detzsize,BeamStopY,BeamStopZ, ...
        simap_data_flag,strcat(OutputFolder,'\verify_afterfit'),rot_angles);
elseif isunix || ismac
    Forward_simu_spots_exp(DS_fit, ...
    Rsample,RecVolumePixel,tomo_scale,ExpTime,atomparam,proj,Spots,rot_start,rot_step, ...
    S,B,Ahkl,nrhkl,hkl_square,Energy,lambda,V,K1,I0E,RotDet,thetamax,lambda_min,lambda_max,Lsam2sou,Lsam2det, ...
    dety00,detz00,P0y,P0z,RotAxisOffset,pixelysize,pixelzsize,dety0,detz0,detysize,detzsize,BeamStopY,BeamStopZ, ...
    simap_data_flag,strcat(OutputFolder,'/verify_afterfit'),rot_angles);
end
