% plot distance difference between simulated and experimental spots

figure;   
subplot(2,3,1);
hold all;
h1 = histogram(Err0);
h2 = histogram(Err_fit);
h1.Normalization = 'probability';
h1.BinWidth = 0.25;
h2.Normalization = 'probability';
h2.BinWidth = 0.25;
xlabel('\Delta_{dis} (pixel)');
ylabel('Frequency');
set(gca,'FontSize',16);
set(gca,'LineWidth',1.5);
box on;
legend('Before fitting','After fitting');
title('(a) Euclidean');
subplot(2,3,2);
hold all;
h1 = histogram(dis_y0);
h2 = histogram(dis_y_fit);
h1.Normalization = 'probability';
h1.BinWidth = 0.25;
h2.Normalization = 'probability';
h2.BinWidth = 0.25;
xlabel('\Delta_{dis} (pixel)');
ylabel('Frequency');
set(gca,'FontSize',16);
set(gca,'LineWidth',1.5);
box on;
legend('Before fitting','After fitting');
title('(b) Horizontal');
subplot(2,3,3);
hold all;
h1 = histogram(dis_z0);
h2 = histogram(dis_z_fit);
h1.Normalization = 'probability';
h1.BinWidth = 0.25;
h2.Normalization = 'probability';
h2.BinWidth = 0.25;
xlabel('\Delta_{dis} (pixel)');
ylabel('Frequency');
set(gca,'FontSize',16);
set(gca,'LineWidth',1.5);
box on;
legend('Before fitting','After fitting');
title('(c) Vertical');   

subplot(2,3,4);
hold all;
h1 = histogram(Err0_all);
h2 = histogram(Err_all_fit);
h1.Normalization = 'probability';
h1.BinWidth = 0.25;
h2.Normalization = 'probability';
h2.BinWidth = 0.25;
xlabel('\Delta_{dis} (pixel)');
ylabel('Frequency');
set(gca,'FontSize',16);
set(gca,'LineWidth',1.5);
box on;
legend('Before fitting','After fitting');
title('(d) Euclidean');
subplot(2,3,5);
hold all;
h1 = histogram(dis_y0_all);
h2 = histogram(dis_y_all_fit);
h1.Normalization = 'probability';
h1.BinWidth = 0.25;
h2.Normalization = 'probability';
h2.BinWidth = 0.25;
xlabel('\Delta_{dis} (pixel)');
ylabel('Frequency');
set(gca,'FontSize',16);
set(gca,'LineWidth',1.5);
box on;
legend('Before fitting','After fitting');
title('(e) Horizontal');
subplot(2,3,6);
hold all;
h1 = histogram(dis_z0_all);
h2 = histogram(dis_z_all_fit);
h1.Normalization = 'probability';
h1.BinWidth = 0.25;
h2.Normalization = 'probability';
h2.BinWidth = 0.25;
xlabel('\Delta_{dis} (pixel)');
ylabel('Frequency');
set(gca,'FontSize',16);
set(gca,'LineWidth',1.5);
box on;
legend('Before fitting','After fitting');
title('(f) Vertical');


